import { useState } from 'react'
import type { AgentConnection } from '../server/agent-connections'
import type { WorkflowNode } from '../server/workflows'
import { api } from './studio-api'

export type ConnectionList = { builtins: string[]; connections: AgentConnection[]; presets: Array<Partial<AgentConnection>>; models: Record<string, string[]>; roles?: Record<string, {engine:string;model:string|null}> }

export function Connections({ list, refresh, report }: { list: ConnectionList; refresh: () => Promise<void>; report: (text: string) => void }) {
  const [editing, setEditing] = useState<Partial<AgentConnection>>({ ...list.presets[0] })
  const [args, setArgs] = useState((editing.args ?? []).join('\n'))
  const [env, setEnv] = useState('')
  const [terminalArgs, setTerminalArgs] = useState('')
  const [probe, setProbe] = useState('')
  const [advanced, setAdvanced] = useState(!editing.command)
  const [busy, setBusy] = useState(false)
  const select = (value: Partial<AgentConnection>) => { setEditing({ ...value }); setArgs((value.args ?? []).join('\n')); setEnv(Object.entries(value.env ?? {}).map(([key, reference]) => `${key}=${reference}`).join('\n')); setTerminalArgs(value.terminalArgs ? value.terminalArgs.join('\n') : ''); setProbe(''); setAdvanced(!value.command) }
  const save = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true)
    try {
      const references = Object.fromEntries(env.split('\n').map(line => line.trim()).filter(Boolean).map(line => { const [key, reference, extra] = line.split('='); if (!key || !reference || extra) throw new Error('Use TARGET_ENV=SOURCE_ENV, one per line'); return [key.trim(), reference.trim()] }))
      const saved = await api<AgentConnection>('/connections', { ...editing, models: (editing.models ?? []).map(model => model.trim()).filter(Boolean), args: args.split('\n').filter(Boolean), env: references, terminalArgs: terminalArgs ? terminalArgs.split('\n').filter(Boolean) : editing.terminalArgs !== undefined ? [] : undefined })
      select(saved); await refresh(); report('AI connection saved. Sign in to its app before running it.')
    } catch (error) { report((error as Error).message) } finally { setBusy(false) }
  }
  return <div className="studio-connections"><aside className="studio-library"><h2>Manage AIs</h2><p>Choose an AI and connect the account or local setup you already use.</p><h3>Built in</h3>{list.builtins.map(id => <div className="studio-list-row" key={id}>{id}<small>Built-in integration</small></div>)}<h3>Configured</h3>{list.connections.map(connection => <button key={connection.id} className="studio-list-row" onClick={() => select(connection)}>{connection.name}<small>Configured</small></button>)}<h3>Add a connection</h3>{list.presets.map(preset => <button key={preset.id} className="studio-list-row" onClick={() => select(preset)}>{preset.name}</button>)}</aside>
    <form className="studio-connection-form" onSubmit={save}><h2>{editing.name || 'New connection'}</h2><p>Choose a preset, install its app, and sign in. Then check the connection. Custom setup is available below.</p>
      <label>Name<input required value={editing.name ?? ''} onChange={event => setEditing({ ...editing, name: event.target.value })} /></label><details open={advanced} onToggle={event => setAdvanced(event.currentTarget.open)}><summary>Advanced connection settings</summary><label>Connection ID<input required value={editing.id ?? ''} onChange={event => setEditing({ ...editing, id: event.target.value })} /></label>
      <label>Adapter<select value={editing.adapter ?? 'acp'} onChange={event => setEditing({ ...editing, adapter: event.target.value as AgentConnection['adapter'] })}><option value="acp">ACP coding agent</option><option value="opencode">OpenCode · API / local models</option><option value="cli">Headless CLI</option></select></label>
      <label>Executable<input required value={editing.command ?? ''} placeholder="qwen" onChange={event => setEditing({ ...editing, command: event.target.value })} /></label>
      <label>Arguments · one per line<textarea rows={3} value={args} onChange={event => setArgs(event.target.value)} /><small>CLI slots: {'{{prompt}}'}, {'{{model}}'}, {'{{session}}'}. Arguments are passed directly, without a shell.</small></label>
      <label>Available model IDs · one per line<textarea rows={3} value={(editing.models ?? []).join('\n')} onChange={event => setEditing({ ...editing, models: event.target.value.split('\n') })} /></label>
      <label>Model family<input value={editing.family ?? ''} placeholder="qwen, grok, llama…" onChange={event => setEditing({ ...editing, family: event.target.value || undefined })} /><small>Used for independent review when a model ID has no recognized family.</small></label>
      {editing.adapter === 'opencode' && <fieldset><legend>Custom OpenAI-compatible endpoint (optional)</legend><label>Base URL<input type="url" value={editing.baseUrl ?? ''} placeholder="http://localhost:11434/v1" onChange={event => setEditing({ ...editing, baseUrl: event.target.value || undefined })} /></label><label>Provider ID<input value={editing.provider ?? 'custom'} onChange={event => setEditing({ ...editing, provider: event.target.value })} /></label><label>API key environment variable<input value={editing.apiKeyEnv ?? ''} placeholder="OPENROUTER_API_KEY" onChange={event => setEditing({ ...editing, apiKeyEnv: event.target.value || undefined })} /></label><small>Leave the endpoint blank to use OpenCode's configured providers. Use provider/model IDs for those providers.</small></fieldset>}
      <label>Environment references<textarea rows={3} value={env} placeholder="API_KEY=MY_PROVIDER_KEY" onChange={event => setEnv(event.target.value)} /><small>Names of variables available to the MC server. Never enter credential values here.</small></label>
      <label>Authentication method (optional)<input value={editing.authMethod ?? ''} onChange={event => setEditing({ ...editing, authMethod: event.target.value || undefined })} /><small>Use a method ID from the capability probe, or leave blank to use the agent's existing sign-in.</small></label>
      {editing.adapter === 'cli' && <label>Output format<select value={editing.output ?? 'text'} onChange={event => setEditing({ ...editing, output: event.target.value as AgentConnection['output'] })}><option value="text">Plain text</option><option value="claude">Claude stream JSON</option><option value="codex">Codex JSON</option></select></label>}
      <label>Interactive terminal arguments · one per line<textarea rows={2} value={terminalArgs} onChange={event => setTerminalArgs(event.target.value)} placeholder="Leave empty for the app’s default interface" /><small>Configure these to also open this agent in an MC terminal. Use {'{{instructions}}'} to pass its workflow instructions.</small></label>
      </details><label className="studio-check"><input type="checkbox" checked={editing.autoApprove === true} onChange={event => setEditing({ ...editing, autoApprove: event.target.checked })} />Allow this AI to use tools without asking each time</label>
      <div className="studio-actions"><button disabled={busy} type="submit">Save connection</button><button disabled={busy || editing.adapter === 'cli' || !list.connections.some(connection => connection.id === editing.id)} type="button" onClick={async () => { setBusy(true); try { setProbe(JSON.stringify(await api(`/connections/${editing.id}/probe`, {}), null, 2)); report('Connection checked. No task was sent.') } catch (error) { report((error as Error).message) } finally { setBusy(false) } }}>Check connection</button></div>{probe && <details><summary>Connection details</summary><pre className="studio-output">{probe}</pre></details>}
    </form></div>
}

export function StepAttachments({node,onChange}:{node:WorkflowNode;onChange:(patch:Partial<WorkflowNode>)=>void}) {
  return <div className="step-attachments">
    <h3>Skills</h3><p>Attach instructions from a Markdown skill file. Its contents are saved with each run.</p>
    {node.skills.map((path,index)=><div className="attachment-row" key={index}><label>Skill file<input value={path} placeholder="Path to SKILL.md" onChange={event=>onChange({skills:node.skills.map((item,i)=>i===index?event.target.value:item)})}/></label><button aria-label={`Remove skill ${index+1}`} onClick={()=>onChange({skills:node.skills.filter((_,i)=>i!==index)})}>×</button></div>)}
    <button onClick={()=>onChange({skills:[...node.skills,'']})}>+ Attach a skill</button>
    <h3>Tools</h3><p>The AI keeps its own tools. Attach additional tools through an ACP connection.</p>
    {node.mcpServers.map((tool,index)=><fieldset className="attachment-card" key={index}><label>Tool name<input value={tool.name} onChange={event=>onChange({mcpServers:node.mcpServers.map((item,i)=>i===index?{...item,name:event.target.value}:item)})}/></label><label>Executable<input value={tool.command} onChange={event=>onChange({mcpServers:node.mcpServers.map((item,i)=>i===index?{...item,command:event.target.value}:item)})}/></label><label>Arguments · one per line<textarea rows={2} value={tool.args.join('\n')} onChange={event=>onChange({mcpServers:node.mcpServers.map((item,i)=>i===index?{...item,args:event.target.value === '' ? [] : event.target.value.split('\n')}:item)})}/></label><div className="tool-environment"><span>Environment variables</span>{Object.entries(tool.env).map(([name,value],at)=><div className="environment-pair" key={at}><input aria-label={`Tool variable ${at+1}`} placeholder="TOOL_KEY" value={name} onChange={event=>onChange({mcpServers:node.mcpServers.map((item,i)=>i===index?{...item,env:Object.fromEntries(Object.entries(item.env).map((pair,j)=>j===at?[event.target.value,pair[1]]:pair))}:item)})}/><input aria-label={`Server variable ${at+1}`} placeholder="SERVER_ENV_NAME" value={value} onChange={event=>onChange({mcpServers:node.mcpServers.map((item,i)=>i===index?{...item,env:{...item.env,[name]:event.target.value}}:item)})}/><button aria-label={`Remove variable ${at+1}`} onClick={()=>onChange({mcpServers:node.mcpServers.map((item,i)=>i===index?{...item,env:Object.fromEntries(Object.entries(item.env).filter((_,j)=>j!==at))}:item)})}>×</button></div>)}<button onClick={()=>onChange({mcpServers:node.mcpServers.map((item,i)=>i===index?{...item,env:{...item.env,'':''}}:item)})}>+ Add environment variable</button></div><small>Use existing environment variable names, never secret values.</small><button onClick={()=>onChange({mcpServers:node.mcpServers.filter((_,i)=>i!==index)})}>Remove tool</button></fieldset>)}
    <button onClick={()=>onChange({mcpServers:[...node.mcpServers,{name:`tool-${node.mcpServers.length+1}`,command:'',args:[],env:{}}]})}>+ Connect a tool</button>
    <h3>Acceptance checks</h3><p>These commands must succeed before this step can pass.</p>
    {node.checks.map((check,index)=><fieldset className="attachment-card" key={index}><label>Command<input value={check.command} onChange={event=>onChange({checks:node.checks.map((item,i)=>i===index?{...item,command:event.target.value}:item)})}/></label><label>Arguments · one per line<textarea rows={2} value={check.args.join('\n')} onChange={event=>onChange({checks:node.checks.map((item,i)=>i===index?{...item,args:event.target.value === '' ? [] : event.target.value.split('\n')}:item)})}/></label><label>Time limit (seconds)<input type="number" min={1} max={3600} value={check.timeoutSeconds} onChange={event=>onChange({checks:node.checks.map((item,i)=>i===index?{...item,timeoutSeconds:Number(event.target.value)}:item)})}/></label><button onClick={()=>onChange({checks:node.checks.filter((_,i)=>i!==index)})}>Remove check</button></fieldset>)}
    <button onClick={()=>onChange({checks:[...node.checks,{command:'',args:[],timeoutSeconds:300}]})}>+ Add a check</button>
  </div>
}
