/** @jsxImportSource @kitajs/html */
import { ENGINE_NAMES } from '../engines'
import type { ModelLists } from '../models'
import type { EngineRoles } from '../secrets'
import { Layout } from './layout'
import { ModelListsScript, ModelPicker } from './model-picker'
export type SettingsProps = { embedded?: boolean; zaiBaseUrl: string; zaiAuthTokenConfigured: boolean; apiTokenConfigured: boolean; bind: string; roles: EngineRoles; autoReview: boolean; models: ModelLists; minPasswordLength: number }
export function SettingsPage(props: SettingsProps): string {
  return Layout({ embedded: props.embedded, title: 'Mission Control — Settings', page: 'app', tab: 'settings', islands: ['nav','forms'], children: <main class="settings-page"><h1>Settings</h1><section><div><h2>Connections</h2><p>Provider access for this workspace.</p></div><div class="settings-fields"><div><strong>Claude</strong><p id="s-claude-auth">Usage status not loaded</p><button type="button" data-probe="claude" data-status="s-msg">Refresh provider status</button></div><div><strong>Codex</strong><p id="s-codex-oauth">Authentication not checked</p><p>Interactive sign-in and binary checks are unavailable here. Use the provider CLI to sign in.</p></div><label for="zaiBaseUrl">Z.ai base URL<input id="zaiBaseUrl" name="zaiBaseUrl" value={props.zaiBaseUrl}/></label><button type="button" data-post="/api/secrets" data-fields="zaiBaseUrl" data-status="s-msg">Save connection</button><div><label for="zaiAuthToken">Z.ai authentication token</label><span id="s-token">{props.zaiAuthTokenConfigured ? 'Configured' : 'Not configured'}</span><input type="password" id="zaiAuthToken" name="zaiAuthToken" placeholder="New token" autocomplete="off" hidden/><button type="button" data-post="/api/secrets" data-fields="zaiAuthToken" data-reveal="zaiAuthToken" data-status="s-msg">Replace token</button><p id="s-glm-conn">Quota status not loaded</p></div></div></section>
  <section><div><h2>Work defaults</h2><p>Applied to future work. A blank model uses the engine default.</p></div><div class="settings-fields">{(['plan','execute','review'] as const).map(role => <div><label for={role}>{role === 'plan' ? 'Plan · new terminals' : role === 'execute' ? 'Execute · new jobs' : 'Review · automatic review'}</label><select id={role} name={role}>{ENGINE_NAMES.map(engine => <option value={engine} selected={engine === props.roles[role].engine}>{engine}</option>)}</select><label for={`${role}_model`}>Model</label><ModelPicker id={`${role}_model`} engineSelectId={role} value={props.roles[role].model} models={props.models} engine={props.roles[role].engine}/></div>)}<label for="autoReview">Automatic review<select id="autoReview" name="autoReview"><option value="off" selected={!props.autoReview}>Off</option><option value="on" selected={props.autoReview}>On</option></select></label><button type="button" data-post="/api/roles" data-fields="plan,execute,review,plan_model,execute_model,review_model,autoReview" data-status="s-msg">Save defaults</button>{ModelListsScript(props.models)}</div></section>
  <section><div><h2>Access</h2><p>Workspace network and API access.</p></div><div class="settings-fields"><label for="bind">Bind address<input id="bind" name="bind" value={props.bind}/></label><button type="button" data-post="/api/secrets" data-fields="bind" data-status="s-msg">Save address</button><div><strong>API token</strong><p id="s-api-token">{props.apiTokenConfigured ? 'Configured' : 'Not configured'}</p><button type="button" data-api-token-reveal="reveal" data-status="s-msg">Copy token</button> <button type="button" data-api-token-rotate="rotate" data-status="s-msg">Rotate token</button></div><p>Password changes are unavailable in this interface.</p></div></section><div class="settings-feedback" id="s-msg" role="status" aria-live="polite">Changes apply to future work.</div></main> })
}
