/** @jsxImportSource @kitajs/html */
import { ModelListsScript, ModelPicker } from './model-picker'
import type { EnginePageProps } from './dispatch'
export function WorkView(mode = 'all', props?: EnginePageProps): JSX.Element {
  return <main class="work-view" id="work-view" data-mode={mode}>
    <aside class="work-nav" aria-label="Work navigator"><div class="work-nav-head"><h1>Work</h1><a class="btn go" href="/dispatch">New job</a></div><label for="work-search">Search work</label><input id="work-search" type="search" placeholder="Label, directory or provider"/><label for="work-filter">Show</label><select id="work-filter"><option value="all">All work</option><option value="active">Active</option><option value="review" selected={mode === 'review'}>Review</option><option value="completed">Completed</option><option value="archived">Archived plans</option></select><div id="work-status" role="status" aria-live="polite">Loading work…</div><div id="work-list"></div></aside>
    <section class="work-detail" aria-label="Selected work"><div id="work-selected"><div class="work-empty"><h2>Select work</h2><p>Choose a conversation or manual plan from the navigator.</p><a class="btn" href="/dispatch">New job</a></div></div>
    {props ? <form id="dispatch-form" class="job-composer"><h1>New job</h1><label for="prompt">What should this job accomplish?</label><textarea id="prompt" name="prompt" required placeholder="Describe the outcome, constraints and verification." rows="7"></textarea><div class="composer-context"><label for="label">Title<input id="label" name="label" placeholder="A short work label"/></label><label for="cwd">Directory<input id="cwd" name="cwd" required placeholder="~/code/project"/></label><label for="engine">Engine<select id="engine" name="engine">{['claude','glm','codex'].map(engine => <option value={engine} selected={engine === props.defaultEngine}>{engine}</option>)}</select></label><label for="model">Model<ModelPicker id="model" engineSelectId="engine" value={props.defaultModel} models={props.models} engine={props.defaultEngine}/></label></div><label class="check"><input type="checkbox" id="worktree" name="worktree" checked/> Isolated worktree</label><div class="composer-actions"><button class="btn go" type="submit">Create job</button><button class="btn" type="button" id="draft-clear">Clear draft</button></div><div id="dispatch-msg" role="status" aria-live="polite"></div>{ModelListsScript(props.models)}</form> : ''}</section>
  </main>
}
