import { lstat, mkdir, readFile, readdir, readlink, rename, stat, symlink, unlink, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { parse } from 'yaml'
import { claudeOnlyScore, CODEX_INSTRUCTIONS_HEADER, translateAgentBody, translateInstructions, translateSkill } from './codex-translate'

export type AssetSyncResult = { linked: string[]; written: string[]; translated: string[]; movedAside: string[]; skipped: string[] }
export type AssetSyncOptions = { claudeDir?: string; codexDir?: string; now?: () => number }

function missing(error: unknown): boolean {
  return typeof error === 'object' && error !== null && 'code' in error && error.code === 'ENOENT'
}

function tomlString(value: string): string {
  return JSON.stringify(value)
}

function parseAgent(markdown: string, fallbackName: string): { name: string; description: string; body: string } | null {
  const match = /^(?:\uFEFF)?---\r?\n([\s\S]*?)^---[ \t]*(?:\r?\n|$)/m.exec(markdown)
  if (!match || match.index !== 0) return null
  try {
    const metadata = parse(match[1]!)
    if (metadata !== null && (typeof metadata !== 'object' || Array.isArray(metadata))) return null
    return {
      name: typeof metadata?.name === 'string' ? metadata.name : fallbackName,
      description: typeof metadata?.description === 'string' ? metadata.description : '',
      body: markdown.slice(match[0].length),
    }
  } catch { return null }
}

const AGENT_MARKER = '# generated by mission-control'

export function agentMarkdownToToml(markdown: string, fallbackName: string): string | null {
  const agent = parseAgent(markdown, fallbackName)
  if (!agent) return null
  const translated = translateAgentBody(agent.body)
  if (translated === null) return null
  const body = translated.replaceAll('"""', '\\"\\"\\"')
  return `name = ${tomlString(agent.name)}\n${AGENT_MARKER}\ndescription = ${tomlString(agent.description)}\ndeveloper_instructions = """\n${body}${body.endsWith('\n') ? '' : '\n'}"""\n`
}

export async function syncEngineAssets(opts: AssetSyncOptions = {}): Promise<AssetSyncResult> {
  const result: AssetSyncResult = { linked: [], written: [], translated: [], movedAside: [], skipped: [] }
  const claudeDir = resolve(opts.claudeDir ?? join(homedir(), '.claude'))
  const codexDir = resolve(opts.codexDir ?? join(homedir(), '.codex'))
  const now = opts.now ?? Date.now
  const skipped = (path: string, error: unknown) => {
    result.skipped.push(`${path} — ${error instanceof Error ? error.message : String(error)}`)
  }
  async function attempt(path: string, action: () => Promise<void>): Promise<void> {
    try {
      await action()
    } catch (error) {
      skipped(path, error)
    }
  }
  async function info(path: string) {
    return lstat(path).catch(error => { if (missing(error)) return null; throw error })
  }
  async function contents(path: string) {
    return readFile(path, 'utf8').catch(error => { if (missing(error)) return null; throw error })
  }
  async function backup(target: string, backupName: string): Promise<void> {
    const path = join(codexDir, 'backup', `${backupName}.pre-mission-control-${now()}`)
    await mkdir(dirname(path), { recursive: true, mode: 0o700 })
    if (await info(path)) throw new Error(`backup already exists: ${path}`)
    await rename(target, path)
    result.movedAside.push(path)
  }
  async function writeChanged(target: string, content: string, translated = false): Promise<void> {
    if ((await info(target))?.isSymbolicLink()) await unlink(target)
    if (await contents(target) === content) return
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, content)
    result.written.push(target)
    if (translated) result.translated.push(target)
  }
  async function link(source: string, target: string, backupName: string): Promise<void> {
    await mkdir(dirname(target), { recursive: true })
    const existing = await info(target)
    if (existing?.isSymbolicLink()) {
      if (resolve(dirname(target), await readlink(target)) === source) return
      await unlink(target)
    } else if (existing) {
      await backup(target, backupName)
    }
    await symlink(source, target)
    result.linked.push(target)
  }
  const instructions = join(claudeDir, 'CLAUDE.md')
  await attempt(instructions, async () => {
    if (!(await stat(instructions)).isFile()) throw new Error('not a file')
    const content = translateInstructions(await readFile(instructions, 'utf8'))
    const target = join(codexDir, 'AGENTS.md')
    await attempt(target, async () => {
      const existing = await info(target)
      if (existing && !existing.isSymbolicLink()) {
        const header = CODEX_INSTRUCTIONS_HEADER.split('\n').slice(0, 2).join('\n')
        if (!existing.isFile() || (await contents(target))?.split('\n').slice(0, 2).join('\n') !== header) {
          await backup(target, 'AGENTS.md')
        }
      }
      await writeChanged(target, content, true)
    })
  })
  const skills = join(claudeDir, 'skills')
  await attempt(skills, async () => {
    for (const entry of await readdir(skills, { withFileTypes: true })) {
      if (entry.name.startsWith('.')) continue
      const source = join(skills, entry.name)
      await attempt(source, async () => {
        if (!entry.isDirectory() && !(entry.isSymbolicLink() && (await stat(source)).isDirectory())) return
        const target = join(codexDir, 'skills', entry.name)
        const markdown = await readFile(join(source, 'SKILL.md'), 'utf8')
        const translated = translateSkill(markdown)
        await attempt(target, async () => {
          if (translated === null) {
            if ((await info(target))?.isSymbolicLink()) await unlink(target)
            skipped(target, 'claude-only')
            return
          }
          if (claudeOnlyScore(markdown) === 0) {
            await link(source, target, join('skills', entry.name))
            return
          }
          const existing = await info(target)
          if (existing?.isSymbolicLink()) await unlink(target)
          else if (existing) {
            const skillFile = join(target, 'SKILL.md')
            const previous = existing.isDirectory() ? await contents(skillFile) : null
            if (!previous?.endsWith(translated.slice(translated.lastIndexOf('<!-- translated for Codex by Mission Control;')))) {
              await backup(target, join('skills', entry.name))
            }
          }
          await mkdir(target, { recursive: true })
          await writeChanged(join(target, 'SKILL.md'), translated, true)
          for (const resource of await readdir(source)) {
            if (resource === 'SKILL.md') continue
            await link(join(source, resource), join(target, resource), join('skills', entry.name, resource))
          }
        })
      })
    }
  })
  const agents = join(claudeDir, 'agents')
  const ignored = new Set(['README', 'AGENTS', 'CLAUDE', 'CONTRIBUTING', 'GEMINI', 'ARCHITECTURE'])
  await attempt(agents, async () => {
    for (const entry of await readdir(agents, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith('.md') || ignored.has(entry.name.slice(0, -3).toUpperCase())) continue
      const source = join(agents, entry.name)
      await attempt(source, async () => {
        const markdown = await readFile(source, 'utf8')
        const agent = parseAgent(markdown, entry.name.slice(0, -3))
        if (!agent) throw new Error('missing or invalid YAML front matter')
        const content = agentMarkdownToToml(markdown, entry.name.slice(0, -3))
        const target = join(codexDir, 'agents', `${entry.name.slice(0, -3)}.toml`)
        await attempt(target, async () => {
          if (content === null) {
            const previous = await contents(target)
            const lines = previous?.split('\n')
            if (lines?.[0] === `name = ${tomlString(agent.name)}` && lines[1] === AGENT_MARKER) await unlink(target)
            skipped(target, 'claude-only')
            return
          }
          await writeChanged(target, content, true)
        })
      })
    }
  })
  return result
}
