import { strict as assert } from 'node:assert'
import { mkdir } from 'node:fs/promises'
import { chromium } from 'playwright'
const browser = await chromium.launch({channel:'chrome',headless:true})
const shots = new URL('./screenshots/', import.meta.url).pathname
await mkdir(shots,{recursive:true})
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}})
  const errors:string[]=[]
  const requests:string[]=[]
  page.on('pageerror',error=>errors.push(error.message))
  page.on('request',request=>{if(new URL(request.url()).pathname.startsWith('/api/'))requests.push(request.url())})
  async function shot(name:string){await page.screenshot({path:`${shots}${name}.png`,fullPage:true})}
  async function noOverflow(){assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Unexpected horizontal overflow')}
  await page.goto('http://localhost:51943/#now')
  await page.getByRole('heading',{name:'Task settings'}).waitFor()
  await shot('now')
  await page.goto('http://localhost:51943/#a')
  await page.getByRole('heading',{name:'How should your team work?'}).waitFor()
  await shot('a-describe')
  await page.getByRole('button',{name:'Browse templates',exact:false}).click()
  await page.getByRole('tab',{name:'All templates'}).waitFor()
  await page.getByRole('button',{name:'MC default',exact:false}).click()
  await page.getByRole('textbox',{name:'Workflow name'}).waitFor()
  assert.equal(await page.locator('.flow-step').count(),4)
  await page.getByRole('button',{name:'Add step',exact:true}).click()
  await page.getByRole('textbox',{name:'Find a step'}).fill('something unique')
  assert.equal(await page.locator('.preset-row').count(),0)
  await page.getByRole('button',{name:'Custom task',exact:false}).waitFor()
  await page.getByRole('textbox',{name:'Find a step'}).fill('')
  await shot('step-presets')
  await page.getByRole('button',{name:'Custom task',exact:false}).click()
  await page.getByRole('textbox',{name:'Step name',exact:true}).fill('My custom task')
  await page.getByRole('textbox',{name:'What should happen?',exact:true}).fill('Inspect the result and write a short report.')
  await shot('custom-step')
  await page.getByRole('button',{name:'Done',exact:true}).click()
  assert.equal(await page.locator('.flow-step').count(),5)
  const card=page.locator('.react-flow__node').first()
  const before=await card.boundingBox()
  assert(before)
  await page.mouse.move(before.x+30,before.y+20)
  await page.mouse.down()
  await page.mouse.move(before.x+60,before.y-35,{steps:8})
  await page.mouse.up()
  const after=await card.boundingBox()
  assert(after&&Math.abs(after.y-before.y)>20,'Node did not move')
  await page.getByRole('button',{name:'Run workflow',exact:true}).click()
  await page.getByText('This is a design preview. Nothing will run.',{exact:true}).waitFor()
  await page.keyboard.press('Escape')
  assert.equal(await page.locator('dialog').count(),0)
  await page.goto('http://localhost:51943/#b')
  await page.getByRole('heading',{name:'What would you like to change?'}).waitFor()
  await shot('b-canvas')
  await page.getByRole('button',{name:'Add a testing step',exact:true}).click()
  assert.equal(await page.locator('.flow-step').count(),5)
  await page.goto('http://localhost:51943/#c')
  await page.getByRole('tab',{name:'All templates'}).waitFor()
  await shot('c-templates')
  await page.getByRole('button',{name:'Research & summarize',exact:false}).click()
  assert.equal(await page.locator('.flow-step').count(),2)
  await page.goto('http://localhost:51943/#a')
  await page.getByRole('textbox',{name:'Describe your workflow'}).fill('Plan, build, and independently review my work.')
  await page.getByRole('button',{name:'Build workflow',exact:true}).click()
  await page.getByText('Illustrative response · no AI call',{exact:true}).waitFor()
  assert.equal(await page.locator('.flow-step').count(),4)
  await noOverflow()
  await page.setViewportSize({width:390,height:844})
  for(const variant of ['a','b','c']){
    await page.goto(`http://localhost:51943/#${variant}`)
    await page.locator('.design-product').waitFor()
    await noOverflow()
    await shot(`mobile-${variant}`)
  }
  assert.deepEqual(errors,[])
  assert.deepEqual(requests,[])
  console.log('Preview check passed: NOW + A/B/C, templates, preset search, custom editing, drag, simulated AI, dialog keyboard dismissal, mobile layout, and zero backend requests.')
} finally { await browser.close() }
