import assert from 'node:assert/strict'
import { mkdtemp, rm } from 'node:fs/promises'
import { homedir, tmpdir } from 'node:os'
import { join } from 'node:path'
import { chromium } from 'playwright'
import { createApp } from '../server/index'
import { createConnectionStore } from '../server/agent-connections'
import { writeConfig } from '../server/secrets'
import { initScratchGitRepo } from '../test/support/scratch-git-repo'

const config = await mkdtemp(join(tmpdir(), 'mc-studio-browser-'))
const repo = await mkdtemp(join(homedir(), 'mc-studio-browser-repo-'))
const previousConfig = process.env.MISSION_CONTROL_CONFIG_DIR
const previousFakeEngines = process.env.MC_FAKE_ENGINES
process.env.MISSION_CONTROL_CONFIG_DIR = config
process.env.MC_FAKE_ENGINES = '1'
await initScratchGitRepo(repo)
const connections = createConnectionStore()
for (const [id, family] of [['fixture-plan', 'claude'], ['fixture-execute', 'qwen'], ['fixture-review', 'gpt']] as const) {
  await connections.save({ id, name: id, adapter: 'acp', command: process.execPath, args: [join(import.meta.dir, '../test/fixtures/agents/acp.ts')], family })
}
await writeConfig({ roles: { plan: { engine: 'fixture-plan', model: null }, execute: { engine: 'fixture-execute', model: null }, review: { engine: 'fixture-review', model: null } } })
const app = await createApp()
app.listen({ hostname: '127.0.0.1', port: 0 })
const url = `http://127.0.0.1:${app.server!.port}`
const browser = await chromium.launch({ headless: true, ...(process.env.MC_TEST_BROWSER ? { executablePath: process.env.MC_TEST_BROWSER } : { channel: 'chrome' }) })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors: string[] = []
const terminalIds: string[] = []
page.on('pageerror', error => errors.push(error.message))
try {
  await page.goto(`${url}/studio`)
  const studio = page.frameLocator('iframe[title="Studio"]')
  await studio.getByRole('heading', { name: 'How should your team work?' }).waitFor()
  await page.screenshot({ path: join(tmpdir(), 'mc-studio-a-home.png'), fullPage: true })
  await studio.getByRole('textbox', { name: 'Describe your workflow' }).fill('Plan, implement, and independently review a change')
  await studio.getByRole('button', { name: 'Build workflow', exact: true }).click()
  await studio.getByRole('textbox', { name: 'Workflow name' }).waitFor({ timeout: 15000 })
  assert.equal(await studio.locator('.flow-step').count(), 4)
  await studio.getByRole('button', { name: 'Save', exact: true }).click()
  await studio.getByText('Workflow saved. Existing runs keep their original version.').waitFor()
  await studio.getByRole('textbox', { name: 'Ask AI to change the workflow' }).fill('Add a testing step before final review')
  await studio.getByRole('button', { name: 'Update flow', exact: true }).click()
  await studio.getByText('Added a testing step', { exact: true }).first().waitFor({ timeout: 15000 })
  assert.equal(await studio.locator('.flow-step').count(), 5)
  await studio.getByRole('button', { name: 'Save', exact: true }).click()
  await studio.getByRole('button', { name: 'Back to workflows', exact: true }).click()
  await studio.getByRole('button', { name: 'Use the default workflow', exact: false }).click()
  await studio.getByRole('button', { name: 'Run workflow', exact: true }).click()
  await studio.getByRole('textbox', { name: 'Run title', exact: true }).fill('Default browser run')
  await studio.getByRole('textbox', { name: 'Project folder', exact: true }).fill(repo)
  await studio.getByRole('textbox', { name: 'What should this run accomplish?', exact: true }).fill('Verify the fixture workflow')
  await studio.getByRole('button', { name: 'Start run', exact: true }).click()
  await studio.locator('.studio-status[data-status="done"]').waitFor({ timeout: 15000 })
  assert.equal(await studio.locator('.studio-attempts > li').count(), 4)
  await studio.getByRole('button', { name: 'Workflows', exact: true }).click()
  await studio.getByRole('button', { name: 'Use the default workflow', exact: false }).click()
  await studio.locator('.flow-step').filter({ hasText: 'Execute' }).click()
  const assignedAi = studio.getByRole('combobox', { name: 'Who should do it?', exact: true })
  const aiChoices = await assignedAi.locator('option').allTextContents()
  assert.equal(aiChoices[0], 'Use default')
  assert.equal(aiChoices.filter(choice => /Planning AI|Execution AI|Review AI/.test(choice)).length, 0)
  assert.equal(aiChoices.filter(choice => choice === 'Claude').length, 1)
  await assignedAi.selectOption('claude')
  assert.equal(await assignedAi.inputValue(), 'claude')
  await assignedAi.selectOption('role:execute')
  await studio.getByRole('button', { name: 'Add next step', exact: true }).click()
  await studio.getByRole('textbox', { name: 'Find a step' }).fill('anything else')
  assert.equal(await studio.locator('.preset-row').count(), 0)
  await studio.getByRole('button', { name: 'Custom task', exact: false }).click()
  await studio.getByRole('textbox', { name: 'Step name', exact: true }).fill('Custom browser checks')
  await studio.getByRole('textbox', { name: 'What should happen?', exact: true }).fill('Run the configured browser checks and report evidence.')
  await studio.getByText('Tools, skills & checks', { exact: true }).click()
  await studio.getByRole('button', { name: '+ Add a check', exact: true }).click()
  await studio.getByRole('textbox', { name: 'Command', exact: true }).fill(process.execPath)
  const checkArguments = studio.locator('.step-attachments').getByRole('textbox', { name: 'Arguments · one per line', exact: true })
  await checkArguments.fill('-e')
  await checkArguments.press('End')
  await checkArguments.press('Enter')
  await checkArguments.pressSequentially('process.stdout.write("acceptance okay")')
  assert.equal(await checkArguments.inputValue(), '-e\nprocess.stdout.write("acceptance okay")')
  await studio.getByRole('textbox', { name: 'Workflow name' }).fill('Custom browser workflow')
  const card = studio.locator('.react-flow__node').filter({ hasText: 'Custom browser checks' })
  const bounds = await card.boundingBox()
  assert(bounds)
  await page.mouse.move(bounds.x + 50, bounds.y + 20)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 85, bounds.y + 60, { steps: 8 })
  await page.mouse.up()
  await studio.getByRole('button', { name: 'Save', exact: true }).click()
  await studio.getByText('Workflow saved. Existing runs keep their original version.').waitFor()
  await page.reload()
  await studio.locator('.saved-workflows').getByRole('button', { name: 'Custom browser workflow', exact: false }).click()
  assert.equal(await studio.locator('.flow-step').count(), 5)
  await studio.getByRole('button', { name: 'Run workflow', exact: true }).click()
  await studio.getByRole('textbox', { name: 'Run title', exact: true }).fill('Custom fixture browser run')
  await studio.getByRole('textbox', { name: 'Project folder', exact: true }).fill(repo)
  await studio.getByRole('textbox', { name: 'What should this run accomplish?', exact: true }).fill('Exercise the configured fixture, without a live browser agent')
  await studio.getByRole('button', { name: 'Start run', exact: true }).click()
  await studio.locator('.studio-status[data-status="done"]').waitFor({ timeout: 15000 })
  assert.equal(await studio.locator('.studio-attempts > li').count(), 5)
  await studio.getByRole('button', { name: 'Manage AIs', exact: true }).click()
  await studio.getByRole('button', { name: 'fixture-plan Configured', exact: true }).click()
  await studio.getByRole('button', { name: 'Check connection' }).click()
  await studio.getByText('Connection checked. No task was sent.').waitFor()
  await studio.getByRole('button', { name: 'Rules', exact: true }).click()
  await studio.getByText('Edit the core prompt', { exact: true }).click()
  await studio.getByRole('textbox', { name: 'Prompt template', exact: true }).fill('Updated team prompt\n{{core_rules}}\n{{workflow}}\n{{assignment}}')
  await studio.getByRole('button', { name: 'Save prompt', exact: true }).click()
  await studio.getByText('Core prompt saved for future runs.').waitFor()
  await studio.getByRole('button', { name: 'Workflows', exact: true }).click()
  await studio.locator('.saved-workflows').getByRole('button', { name: 'Custom browser workflow', exact: false }).click()
  await page.screenshot({ path: join(tmpdir(), 'mc-studio-desktop.png'), fullPage: true })
  await studio.getByRole('button', { name: 'Back to workflows', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  const frame = page.frames().find(frame => frame.url().includes('/studio?embed=1'))!
  assert(await frame.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1))
  assert((await studio.getByRole('textbox', { name: 'Describe your workflow' }).boundingBox())!.width >= 300)
  await page.screenshot({ path: join(tmpdir(), 'mc-studio-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('link', { name: 'Terminals', exact: true }).click()
  for (const workflow of ['Default workflow', 'Custom browser workflow']) {
    await page.getByRole('button', { name: 'New terminal', exact: true }).click()
    const picker = page.getByRole('combobox', { name: 'Workflow', exact: true })
    await picker.locator('option').filter({ hasText: 'Custom browser workflow' }).waitFor({ state: 'attached' })
    if (workflow === 'Default workflow') assert.equal(await picker.inputValue(), '')
    else await picker.selectOption({ label: workflow })
    await page.locator('#term-engines [data-engine="claude"]').click()
    await page.locator('#term-cwd').fill(repo)
    const created = page.waitForResponse(response => response.url().endsWith('/api/terminals') && response.request().method() === 'POST')
    await page.locator('#term-form').getByRole('button', { name: 'Open terminal', exact: true }).click()
    const terminal = await (await created).json()
    terminalIds.push(terminal.id)
    assert.equal(terminal.workflow.name, workflow === 'Default workflow' ? 'Plan, verify, execute, review' : workflow)
    await page.locator('.terminal-panel:not([hidden]) .session-workflow').filter({ hasText: workflow }).waitFor()
  }
  await page.getByRole('button', { name: 'Side by side', exact: true }).click()
  assert.equal(await page.locator('.terminal-panel:not([hidden]) .session-workflow').count(), 2)
  await page.screenshot({ path: join(tmpdir(), 'mc-terminal-workflows.png'), fullPage: true })
  await page.reload()
  await page.locator('.session-workflow').filter({ hasText: 'Custom browser workflow' }).waitFor()
  await page.locator('.session-workflow').filter({ hasText: 'Default workflow' }).waitFor()
  const sessions = (await (await page.request.get(`${url}/api/terminals`)).json()).sessions
  const customTerminal = sessions.find((session: { id: string }) => session.id === terminalIds[1])
  assert((await page.request.post(`${url}/api/studio/default`, { data: { id: customTerminal.workflow.id, revision: customTerminal.workflow.revision } })).ok())
  await page.getByRole('button', { name: 'New terminal', exact: true }).click()
  const standardChoice = page.getByRole('combobox', { name: 'Workflow', exact: true })
  await standardChoice.locator('option').filter({ hasText: 'MC standard' }).waitFor({ state: 'attached' })
  assert.equal(await standardChoice.locator('option:checked').textContent(), 'Default workflow · Custom browser workflow')
  await standardChoice.selectOption({ label: 'MC standard · Plan, verify, execute, review' })
  await page.locator('#term-engines [data-engine="claude"]').click()
  await page.locator('#term-cwd').fill(repo)
  const openedStandard = page.waitForResponse(response => response.url().endsWith('/api/terminals') && response.request().method() === 'POST')
  await page.locator('#term-form').getByRole('button', { name: 'Open terminal', exact: true }).click()
  const standardTerminal = await (await openedStandard).json()
  terminalIds.push(standardTerminal.id)
  assert.equal(standardTerminal.workflow.id, 'default')
  assert.deepEqual(errors, [])
  console.log('Studio browser check passed: A home, drafting/editing, workflow runs, presets, connections, prompt versions, mobile layout, independent default/custom terminal workflows, original default after changing the workspace default, and reload persistence; local fixtures only.')
} catch (error) {
  console.error('Browser errors:', errors)
  await page.screenshot({ path: join(tmpdir(), 'mc-studio-failure.png'), fullPage: true })
  throw error
} finally {
  for (const id of terminalIds) await page.request.delete(`${url}/api/terminals/${id}`)
  await browser.close()
  void app.stop(true)
  if (previousConfig === undefined) delete process.env.MISSION_CONTROL_CONFIG_DIR; else process.env.MISSION_CONTROL_CONFIG_DIR = previousConfig
  if (previousFakeEngines === undefined) delete process.env.MC_FAKE_ENGINES; else process.env.MC_FAKE_ENGINES = previousFakeEngines
  await rm(config, { recursive: true, force: true })
  await rm(repo, { recursive: true, force: true })
}

process.exit(0)
